"use client";

import store from "@/lib/store";
import "./globals.css";

import { Provider } from "react-redux";
import FileUpload from "@/components/FileUpload";
import Main from "@/components/Main";



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-800 ">
        <Provider store={store}>
          <Main />


          <main className="container mx-auto p-4">{children}</main>
        </Provider>

      </body>
    </html>
  );
}
